name: Demo
on: [push]

jobs:
  my-job:
    name: myFirstJob
    runs-on: ubuntu-latest
    steps:
    - name: stepOne
      env:
        MY_VAR: Hello World,
        MY_VAR2: I'm
        MY_NAME: CodeGorgeous
      run: |
        echo $MY_VAR $MY_VAR2 $MY_NAME.
