name: Demo
on: [push]

jobs:
  my-job:
    name: myFirstJob
    runs-on: ubuntu-latest
    steps:
    - name: stepOne
      env:
        MY_NAME: CodeGorgeous
      run: |
        echo Hello World, I'm $MY_NAME.
